[project]
name = "connect-matrix"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.affiliate-network]
path = "contracts/affiliate-network.clar"
depends_on = []

[contracts.network-rankings]
path = "contracts/network-rankings.clar"
depends_on = []

[contracts.reward-distributor]
path = "contracts/reward-distributor.clar"
depends_on = []

[contracts.network-offerings]
path = "contracts/network-offerings.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
